export const sidebar = {
	display: 'flex',
	flexDirection: 'column',
	justifyContent: 'space-between',
	alignItems: 'center',
	width: '5rem',
	marginTop: '1rem',
	marginBottom: '1rem',
	paddingTop: '0.5rem',
	paddingBottom: '30px',
	marginLeft: '1rem',
	// backgroundColor: '#f7f8fa',
	borderRadius: '20px',
	// boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.1)',
};
