export const categories = {
	food_and_drink: 'Food and Drink',
	travel: 'Travel',
	recreation: 'Recreation',
	service: 'Service',
	shops: 'Shops',
	transfer: 'Transfer',
	healthcare: 'Healthcare',
	payment: 'Payment',
	community: 'Community',
	tax: 'Tax',
	interest: 'Interest',
	bank_fees: 'Bank Fees',
	rent_and_utilities: 'Rent and Utilities',
	subscription: 'Subscription',
	groceries: 'Groceries',
	entertainment: 'Entertainment',
	transportation: 'Transportation',
	savings: 'Savings',
	investments: 'Investments',
	education: 'Education',
	charity: 'Charity',
	loan: 'Loan',
	others: 'Others',
};
